import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Generative UI with LangGraph",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="antialiased font-sans">
                {children}
            </body>
        </html>
    );
}
